[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = false

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
bsc_testnet = "${BSC_TESTNET_RPC_URL}"
bsc_mainnet = "${BSC_MAINNET_RPC_URL}"

[etherscan]
bsc_testnet = { key = "${BSCSCAN_API_KEY}", chain = 97, url = "https://api-testnet.bscscan.com/api" }
bsc_mainnet = { key = "${BSCSCAN_API_KEY}", chain = 56, url = "https://api.bscscan.com/api" }
